name: BatteryAPI
targets:
  BatteryAPI:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Sources]
    info:
      path: ./Info.plist
      version: 0.0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
